### ISSUE TITLE
No cabal file in '.' when styx.yaml is not in same location with cabal

### ISSUE THREAD

**Issue by revskill10** [jyp/styx#14]
I created the project structure like this:
```
- styx.yaml
- apps
- deps
```
My `styx.yaml` is
```yml
local-packages:
  helloworld:
    location: apps/helloworld
  katip-helpers:
    location: deps/katip-helpers
```
When i run `styx build`, i got error
```
cabal: Error reading local package.
Couldn't find .cabal file in: .
```
